package com.quill.ui.theme

import androidx.compose.ui.graphics.Color

// Quill parchment palette — derived from Stitch design system
val Surface = Color(0xFFFAF9F4)
val OnSurface = Color(0xFF2F342D)
val Primary = Color(0xFF5D5F5A)
val OnPrimary = Color(0xFFF8F8F2)
val PrimaryContainer = Color(0xFFE3E3DD)
val OnPrimaryContainer = Color(0xFF51524E)
val Secondary = Color(0xFF5E5F5B)
val OnSecondary = Color(0xFFFAF9F2)
val SecondaryContainer = Color(0xFFE3E3DC)
val OnSecondaryContainer = Color(0xFF51524D)
val Tertiary = Color(0xFF5A6152)
val OnTertiary = Color(0xFFF5FCE8)
val TertiaryContainer = Color(0xFFEFF6E2)
val OnTertiaryContainer = Color(0xFF575E4F)
val Error = Color(0xFF9E422C)
val OnError = Color(0xFFFFF7F6)
val ErrorContainer = Color(0xFFFE8B70)
val OnErrorContainer = Color(0xFF742410)
val Background = Color(0xFFFAF9F4)
val OnBackground = Color(0xFF2F342D)
val SurfaceVariant = Color(0xFFE0E4D9)
val OnSurfaceVariant = Color(0xFF5C6058)
val Outline = Color(0xFF787C73)
val OutlineVariant = Color(0xFFAFB3AA)
val SurfaceDim = Color(0xFFD7DCD0)
val SurfaceBright = Color(0xFFFAF9F4)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF4F4EE)
val SurfaceContainer = Color(0xFFEDEFE7)
val SurfaceContainerHigh = Color(0xFFE7E9E0)
val SurfaceContainerHighest = Color(0xFFE0E4D9)
val InverseSurface = Color(0xFF0D0F0C)
val InverseOnSurface = Color(0xFF9D9D99)
val InversePrimary = Color(0xFFFDFDF6)
val SurfaceTint = Color(0xFF5D5F5A)
